### ISSUE TITLE
code.py clashes with PyCharms Debug mode.

### ISSUE THREAD

**Issue by miron** [tecladocode/complete-python-course#39]
When debugging the lecture files named code.py, PyCharms debugger crashes because it uses a code module itself:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.1.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_console_integration.py", line 4, in <module>
    from code import InteractiveConsole, InteractiveInterpreter
ImportError: cannot import name 'InteractiveConsole' from 'code' (C:\Users\Mir\complete-python-course\course_contents\10_advanced_python\lectures\16_higher_order_functions\code.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.1.1\plugins\python\helpers\pydev\pydevd.py", line 45, in <module>
    from _pydevd_bundle.pydevd_comm import CMD_SET_BREAK, CMD_SET_NEXT_STATEMENT, CMD_STEP_INTO, CMD_STEP_OVER, \
  File "C:\Program Files\JetBrains\PyCharm 2022.1.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 91, in <module>
    from _pydevd_bundle import pydevd_console_integration
  File "C:\Program Files\JetBrains\PyCharm 2022.1.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_console_integration.py", line 6, in <module>
    from _pydevd_bundle.pydevconsole_code_for_ironpython import IronPythonInteractiveConsole as InteractiveConsole, \
  File "C:\Program Files\JetBrains\PyCharm 2022.1.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevconsole_code_for_ironpython.py", line 305
    exec code in self.locals
    ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'exec'. Did you mean exec(...)?
```

Solution: Rename all code.py files to something else.

**Comment by jslvtr** [comment]
Thank you for this!
